os: Visual Studio 2015

configuration: Debug
matrix:
  fast_finish: true

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 12" ..
  - cmake --build . --config Debug --clean-first
